//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testthithu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Sanpham
    {
        public Sanpham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.MauSac = new HashSet<MauSac>();
        }
    
        public int SanphamID { get; set; }
        public string TenSanpham { get; set; }
        public string MoTa { get; set; }

        [Required(ErrorMessage = "Giá sản phẩm là bắt buộc.")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Giá chỉ được nhập số.")]
        public decimal Gia { get; set; }
        public Nullable<byte> TrangThai { get; set; }

        [Required(ErrorMessage = "Vui lòng chọn ảnh.")]
        
        public string AnhDaiDien { get; set; }
        public Nullable<byte> NoiBat { get; set; }
        public Nullable<int> PhanLoaiSanPhamID { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        public virtual ICollection<MauSac> MauSac { get; set; }
    }
}
