//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBookStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBanSachEntities2 : DbContext
    {
        public QLBanSachEntities2()
            : base("name=QLBanSachEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDONTHANG> CHITIETDONTHANG { get; set; }
        public DbSet<CHUDE> CHUDE { get; set; }
        public DbSet<DONDATHANG> DONDATHANG { get; set; }
        public DbSet<KHACHHANG> KHACHHANG { get; set; }
        public DbSet<NHAXUATBAN> NHAXUATBAN { get; set; }
        public DbSet<SACH> SACH { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TACGIA> TACGIA { get; set; }
        public DbSet<VIETSACH> VIETSACH { get; set; }
    }
}
