//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testDeThi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyBanQuanAoEntities : DbContext
    {
        public QuanLyBanQuanAoEntities()
            : base("name=QuanLyBanQuanAoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ChiTietDonHang> ChiTietDonHang { get; set; }
        public DbSet<ChiTietSanPhamMua> ChiTietSanPhamMua { get; set; }
        public DbSet<DonHang> DonHang { get; set; }
        public DbSet<Khachhang> Khachhang { get; set; }
        public DbSet<MauSac> MauSac { get; set; }
        public DbSet<PhanLoaiSanPham> PhanLoaiSanPham { get; set; }
        public DbSet<Sanpham> Sanpham { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
