//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dethithu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietSanPhamMua
    {
        public int ChiTietSanPhamMuaID { get; set; }
        public Nullable<int> ChiTietDonHangID { get; set; }
        public Nullable<int> MauSacID { get; set; }
    
        public virtual ChiTietDonHang ChiTietDonHang { get; set; }
        public virtual MauSac MauSac { get; set; }
    }
}
