//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dethithu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
        }
    
        public int DonHangID { get; set; }
        public Nullable<int> KhachhangID { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public decimal TongTien { get; set; }
        public string PTThanhToan { get; set; }
        public Nullable<byte> TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual Khachhang Khachhang { get; set; }
    }
}
