//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dethithu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanLoaiSanPham
    {
        public PhanLoaiSanPham()
        {
            this.Sanpham = new HashSet<Sanpham>();
        }
    
        public int PhanLoaiSanPhamID { get; set; }
        public string TenPhanLoai { get; set; }
    
        public virtual ICollection<Sanpham> Sanpham { get; set; }
    }
}
