//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dethithu.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sanpham
    {
        public Sanpham()
        {
            this.ChiTietDonHang = new HashSet<ChiTietDonHang>();
            this.MauSac = new HashSet<MauSac>();
        }
    
        public int SanphamID { get; set; }
        [Display(Name ="Tên sản phẩm")]
        public string TenSanpham { get; set; }
        [Display(Name ="Mô tả")]
        public string MoTa { get; set; }
        [Display(Name ="Giá")]
        public decimal Gia { get; set; }
        [Display(Name ="Trạng thái")]
        public Nullable<byte> TrangThai { get; set; }
        [Display(Name ="Ảnh đại diện")]
        public string AnhDaiDien { get; set; }
        [Display(Name ="Nổi bật")]
        public Nullable<byte> NoiBat { get; set; }
        [Display(Name ="Phân loại sản phẩm")]
        public Nullable<int> PhanLoaiSanPhamID { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHang { get; set; }
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        public virtual ICollection<MauSac> MauSac { get; set; }
    }
}
